pref('extensions.6d504ebFhRf8dHkt1e150ac4k91757f@korpuslex.default',	'[{"dico":"wordreference","langPair":"enfr # English French","tts":["responsivevoiceorg","UK English Female # "]}]');

pref('extensions.6d504ebFhRf8dHkt1e150ac4k91757f@korpuslex.langPair','[{"almaany": "fr # french","artfl": "dvlf # Dictionnaire vivant de la langue franÃ§aise","babla": "english-french # ","beolingus": "syn # Synonyms","cedict": "Simplified # Chinese Pinyin English","chambers": "21st # 21st century dictionary","cnrtl": "Lexicographie # TLFi","collins": "english-french # ","corriere":"SabCol # dizionaro (Sabatini-Coletti)","dictcc": "dees # German Spanish","dictionarycom": "english french # translate","dsal":"Hayyim # Persian English DSAl","duden": " # ","dwds": " # ","eurovoc": "en # (en) English","googletranslate": "en # English English","gramota":" # ","iate": "en # English","ispeech": "usenglishfemale # US English Female","jmdict":"JMDict # Japanese-Multilingual dictionary","larousse": " # ","leodict": "ende # english german","linguatec": "FRF # French FranÃ§ais","linguee": "english-french # ","littre": " #  Ed. 1872-1877","memidex": " # ","merriamwebster": "Dictionary # ","oxforddictionaries": "english # British and World English","pons": "defr # German French","raes": "DESEN # Diccionario esencial (RAEs)","responsivevoiceorg":"UK English Female # ","reverso": "english-french # ","sapere":"Italiano # dizionaro","thefreedictionary": "fr # french","treccani":"Vocabolario # ","triantafyllides":"Triantafyllides # Dictionary of Standard Modern Greek","urbandictionary": "  # ","wordreference": "enes # English Spanish","wortschatzunileipzig": "swa_newscrawl_2011 # Swahili","woxikon": "deutsch-franzoesisch # French","notes":" # "}]');

pref('extensions.6d504ebFhRf8dHkt1e150ac4k91757f@korpuslex.rankDict',	'[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,34,35,36,37,38,39,40,41]');

pref('extensions.6d504ebFhRf8dHkt1e150ac4k91757f@korpuslex.hotkeysConfig','[{"selection":"mouseup","modifier":"s","console":"F8","popupIcons":true, "showContextMenu":true, "languageDetectionWebService":"detectLanguageCom","showNote:true"}]');

pref('extensions.6d504ebFhRf8dHkt1e150ac4k91757f@korpuslex.consolePosition',	'[{"top":109,"left":1}]');

